# Generated by Django 6.0.1 on 2026-01-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
