# Generated by Django 6.0.1 on 2026-01-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_pharmacy_remove_user_phone_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PHARMACY', 'Pharmacy'), ('CLIENT', 'Client')], default='CLIENT', max_length=20),
        ),
    ]
